server:
  port: 8989

spring:
  application:
    name: turbine

#turbine:
#  aggregator:
#    clusterConfig: BIFROST-GATEWAY
#  appConfig: /gateway/gateway-gateway

turbine:
  aggregator:
    clusterConfig: ZUUL-GATEWAY, CUSTOMER
  appConfig: zuul-gateway, customer
  cluster-name-expression: new String("default")
  combine-host-port: true
  instanceUrlSuffix:
    ZUUL-GATEWAY: actuator/hystrix.stream

eureka:
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
      base-path: /actuator
      cors:
        allowed-origins: true