server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/douglas-DS/microservices-cloud-config
  application:
    name: config-server

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    service-url:
      defultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    register-with-eureka: true
    fetch-registry: false
